# Generated by Django 5.1.2 on 2024-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_small', models.CharField(default='(Link do Poster)', max_length=255)),
                ('thumbnail_medium', models.CharField(default='(Link do Poster)', max_length=255)),
                ('thumbnail_large', models.CharField(default='(Link do Poster)', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=50)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
            ],
        ),
    ]
